#%RAML 1.0 NamedExample
cuponExample:
  JOLLY15: Get off 15 rupees in each trip.
  GIFTGUIDE: GET Amazon Gift Card in each trip. 
  RESOLUTE:   Get a chance to visit Resolute Jupiter 2.
  CENTAURI: Get 50% off to lucky winner.