hotel:
  wsdl: "http://hotelbooking.us-e2.cloudhub.io//TajGroup/default_Port?wsdl"
  service: "TajGroup"
  port: "default_Port"
  
car:
  url: "carbooking.us-e2.cloudhub.io"
  port: '80'
  protocol: 'HTTP'
  basepath: '/'
  
flight:
  url: "flightbookingindigo.us-e2.cloudhub.io"
  port: '80'
  protocol: 'HTTP'
  basepath: '/api'
  client_id : "1234"
  client_secret: "1234"
  
